import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export interface AquaAlert {
  id: string;
  location: string;
  village: string;
  level: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL';
  score: number;
  action: string;
  status: 'Pending Approval' | 'Monitoring' | 'Approved' | 'Rejected';
  timestamp: string;
  autoGenerated: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class AlertService {

  /**
   * Risk threshold for automatic alerts.
   *
   * Alert is generated ONLY when risk is ABOVE 70.
   * 70 = no alert
   * 71+ = alert
   */
  private readonly ALERT_THRESHOLD = 70;

  /**
   * Stores all generated alerts.
   */
  private alertsSubject = new BehaviorSubject<AquaAlert[]>(
    this.loadAlerts()
  );

  /**
   * Components can subscribe to alerts.
   */
  alerts$ = this.alertsSubject.asObservable();

  /**
   * Prevents duplicate alerts while a zone
   * remains above the threshold.
   */
  private alertedZones = new Set<string>();

  constructor() {

    /**
     * Restore already-alerted zones from localStorage.
     */
    const existingAlerts = this.alertsSubject.value;

    existingAlerts.forEach(alert => {

      if (
        alert.score > this.ALERT_THRESHOLD &&
        alert.status !== 'Rejected'
      ) {
        this.alertedZones.add(alert.village);
      }

    });

    /**
     * Ask for browser notification permission.
     */
    this.requestNotificationPermission();
  }

  /**
   * Returns all current alerts.
   */
  getAlerts(): AquaAlert[] {
    return this.alertsSubject.value;
  }

  /**
   * Check whether a risk score should trigger
   * a new automatic alert.
   */
  shouldTriggerAlert(
    village: string,
    score: number
  ): boolean {

    /**
     * 70 or below = NO ALERT
     */
    if (score <= this.ALERT_THRESHOLD) {
      return false;
    }

    /**
     * Already alerted = don't duplicate.
     */
    if (this.alertedZones.has(village)) {
      return false;
    }

    return true;
  }

  /**
   * Automatically creates an alert when
   * risk goes ABOVE 70.
   */
  createAutomaticAlert(
    location: string,
    village: string,
    score: number,
    action?: string
  ): AquaAlert | null {

    if (!this.shouldTriggerAlert(village, score)) {
      return null;
    }

    const alert: AquaAlert = {

      id: this.generateAlertId(),

      location,

      village,

      level: this.getAlertLevel(score),

      score: Math.round(score),

      action:
        action ||
        this.getRecommendedAction(score),

      status: 'Pending Approval',

      timestamp: new Date().toISOString(),

      autoGenerated: true
    };

    /**
     * Lock this zone so that the same
     * alert isn't generated every 5 minutes.
     */
    this.alertedZones.add(village);

    /**
     * Add newest alert at the top.
     */
    const updatedAlerts = [
      alert,
      ...this.alertsSubject.value
    ];

    this.alertsSubject.next(updatedAlerts);

    /**
     * Save to localStorage.
     */
    this.saveAlerts(updatedAlerts);

    /**
     * Show browser notification.
     */
    this.showBrowserNotification(alert);

    return alert;
  }

  /**
   * Approve an alert.
   */
  approveAlert(id: string): void {

    const updatedAlerts =
      this.alertsSubject.value.map(alert => {

        if (alert.id === id) {
          return {
            ...alert,
            status: 'Approved' as const
          };
        }

        return alert;
      });

    this.alertsSubject.next(updatedAlerts);

    this.saveAlerts(updatedAlerts);
  }

  /**
   * Reject an alert.
   */
  rejectAlert(id: string): void {

    const updatedAlerts =
      this.alertsSubject.value.map(alert => {

        if (alert.id === id) {
          return {
            ...alert,
            status: 'Rejected' as const
          };
        }

        return alert;
      });

    this.alertsSubject.next(updatedAlerts);

    this.saveAlerts(updatedAlerts);
  }

  /**
   * Mark an alert as monitoring.
   */
  markMonitoring(id: string): void {

    const updatedAlerts =
      this.alertsSubject.value.map(alert => {

        if (alert.id === id) {
          return {
            ...alert,
            status: 'Monitoring' as const
          };
        }

        return alert;
      });

    this.alertsSubject.next(updatedAlerts);

    this.saveAlerts(updatedAlerts);
  }

  /**
   * Remove an alert.
   */
  removeAlert(id: string): void {

    const alertToRemove =
      this.alertsSubject.value.find(
        alert => alert.id === id
      );

    const updatedAlerts =
      this.alertsSubject.value.filter(
        alert => alert.id !== id
      );

    this.alertsSubject.next(updatedAlerts);

    this.saveAlerts(updatedAlerts);

    /**
     * Allow the zone to generate another alert
     * after the old alert is removed.
     */
    if (alertToRemove) {
      this.alertedZones.delete(
        alertToRemove.village
      );
    }
  }

  /**
   * Returns alert level based on risk score.
   */
  private getAlertLevel(
    score: number
  ): AquaAlert['level'] {

    if (score >= 81) {
      return 'CRITICAL';
    }

    if (score > 70) {
      return 'HIGH';
    }

    if (score >= 31) {
      return 'MODERATE';
    }

    return 'LOW';
  }

  /**
   * Default recommended action.
   */
  private getRecommendedAction(
    score: number
  ): string {

    if (score >= 81) {
      return 'Immediate field verification and evacuation readiness';
    }

    if (score > 70) {
      return 'Inspect vulnerable roads and prepare local response teams';
    }

    if (score >= 31) {
      return 'Monitor rainfall and drainage conditions';
    }

    return 'Continue routine monitoring';
  }

  /**
   * Generates IDs:
   * ALT-001
   * ALT-002
   * ALT-003
   */
  private generateAlertId(): string {

    const existingAlerts =
      this.alertsSubject.value;

    const numbers = existingAlerts
      .map(alert => {

        const match =
          alert.id.match(/ALT-(\d+)/);

        return match
          ? Number(match[1])
          : 0;
      });

    const nextNumber =
      Math.max(0, ...numbers) + 1;

    return `ALT-${String(nextNumber).padStart(3, '0')}`;
  }

  /**
   * Save alerts locally.
   */
  private saveAlerts(
    alerts: AquaAlert[]
  ): void {

    try {

      localStorage.setItem(
        'aquasentinel_alerts',
        JSON.stringify(alerts)
      );

    } catch {
      // Ignore storage errors.
    }
  }

  /**
   * Load saved alerts.
   */
  private loadAlerts(): AquaAlert[] {

    try {

      const saved =
        localStorage.getItem(
          'aquasentinel_alerts'
        );

      if (!saved) {
        return [];
      }

      return JSON.parse(saved);

    } catch {

      return [];
    }
  }

  /**
   * Show browser notification.
   */
  private showBrowserNotification(
    alert: AquaAlert
  ): void {

    if (
      typeof window === 'undefined' ||
      !('Notification' in window)
    ) {
      return;
    }

    /**
     * If permission hasn't been granted yet,
     * request it and then show notification.
     */
    if (Notification.permission === 'default') {

      Notification.requestPermission()
        .then(permission => {

          if (permission === 'granted') {
            this.displayNotification(alert);
          }

        });

      return;
    }

    /**
     * Permission already granted.
     */
    if (Notification.permission === 'granted') {
      this.displayNotification(alert);
    }
  }

  /**
   * Actually creates the browser notification.
   */
  private displayNotification(
    alert: AquaAlert
  ): void {

    const notification =
      new Notification(
        `🚨 AquaSentinel ${alert.level} Alert`,
        {
          body:
            `${alert.village}: Risk score ${alert.score}.\n` +
            `${alert.action}`,

          icon: '/favicon.ico',

          tag: `aquasentinel-${alert.village}`,

          requireInteraction:
            alert.level === 'CRITICAL'
        }
      );

    /**
     * Clicking the notification focuses the app.
     */
    notification.onclick = () => {

      window.focus();

      notification.close();
    };
  }

  /**
   * Ask browser for notification permission.
   */
  requestNotificationPermission(): void {

    if (
      typeof window === 'undefined' ||
      !('Notification' in window)
    ) {
      return;
    }

    if (
      Notification.permission === 'default'
    ) {

      Notification.requestPermission()
        .then(permission => {

          console.log(
            'AquaSentinel notification permission:',
            permission
          );

        });

    }
  }

  /**
   * Reset alert lock when risk falls
   * back to 70 or below.
   */
  resetZoneAlert(village: string): void {

    this.alertedZones.delete(village);
  }

  /**
   * Returns current alert threshold.
   */
  getAlertThreshold(): number {

    return this.ALERT_THRESHOLD;
  }
}